#ifndef CONFIG_H
#define CONFIG_H

#define HAVE_IN_PKTINFO 1
#define HAVE_ADDRINFO_STRUCT 1
#define HAVE_TIMESPEC_STRUCT 1
#define HAVE_SOCKADDR_DL_STRUCT
#define HAVE_STRUCT_IFREQ_IFR_MTU
#undef HAVE_SOCKADDR_SA_LEN


#endif  /* CONFIG_H */
